In [1]:
import sys
sys.path.append('..')
from scipy.stats import spearmanr, kendalltau
from utils.results import *

In [2]:
'''
IPython extension to reload modules before executing user code.
https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html
'''
%load_ext autoreload
%autoreload 2

In [3]:
sem_labels = ['kitchen', 'dogs', 'cats', 'wearable', 'transport', 'birds']
sem_labels_plot = ['', 'kitchen\nitems', 'dogs', 'cats', 'wearable\nitems', 'land\ntransport', 'birds']
df_sem = context_summary('sem', 2, 9)
df_sem.insert(0, 'label', sem_labels)
df_sem

,label,size,similarity,acc_base_in,acc_base_out,acc_trained_in,acc_trained_out,acc_change_in,acc_change_out,num_epochs
0,kitchen,35,0.446404,0.512884,0.650968,0.670401,0.527051,0.157517,-0.123917,92
1,dogs,129,0.553892,0.661100,0.643919,0.684884,0.621002,0.023784,-0.022917,31
2,cats,13,0.854177,0.708477,0.645314,0.782407,0.582139,0.073930,-0.063175,134
3,wearable,56,0.432272,0.535303,0.652710,0.660537,0.543158,0.125234,-0.109552,71
4,transport,45,0.428524,0.715678,0.642858,0.773848,0.599449,0.058171,-0.043409,65
5,birds,60,0.534972,0.824636,0.634741,0.863222,0.605363,0.038586,-0.029379,53

In [4]:
x = [df_sem['acc_base_in'], df_sem['size'], df_sem['similarity']]
y = df_sem['acc_change_in']
df_corr = pd.DataFrame({
    'property': ['difficulty', 'size', 'similarity'],
    'rho_spearman': [spearmanr(x_i, y).correlation for x_i in x],
    'pval_spearman': [spearmanr(x_i, y).pvalue for x_i in x],
    'tau_kendall': [kendalltau(x_i, y).correlation for x_i in x],
    'pval_kendall': [kendalltau(x_i, y).pvalue for x_i in x]})
df_corr.round(decimals=2)

     property  rho_spearman  pval_spearman  tau_kendall  pval_kendall
0  difficulty         -0.66           0.16         -0.6          0.09
1        size         -0.71           0.11         -0.6          0.09
2  similarity         -0.31           0.54         -0.2          0.57

In [5]:
df_diff = context_summary(type_context='diff', version_wnids=2, version_weights=3)
df_size_v6 = context_summary(type_context='size', version_wnids=4, version_weights=6).iloc[1:]
df_size_v7 = context_summary(type_context='size', version_wnids=5, version_weights=7).iloc[1:]
df_size = pd.concat((df_size_v6, df_size_v7), axis=0)
df_sim_v3 = context_summary(type_context='sim', version_wnids=3, version_weights=3)
df_sim_v4 = context_summary(type_context='sim', version_wnids=4, version_weights=4)
df_sim = pd.concat((df_sim_v3, df_sim_v4), axis=0)

In [6]:
x = [df_diff['acc_base_in'], df_size['size'], df_sim['similarity']]
y = [df_diff['acc_change_in'], df_size['acc_change_in'], df_sim['acc_change_in']]
df_corr = pd.DataFrame({
    'property': ['difficulty', 'size', 'similarity'],
    'rho_spearman': [spearmanr(x_i, y_i).correlation for (x_i, y_i) in zip(x, y)],
    'pval_spearman': [spearmanr(x_i, y_i).pvalue for (x_i, y_i) in zip(x, y)],
    'tau_kendall': [kendalltau(x_i, y_i).correlation for (x_i, y_i) in zip(x, y)],
    'pval_kendall': [kendalltau(x_i, y_i).pvalue for (x_i, y_i) in zip(x, y)]})
df_corr.round(decimals=2)

     property  rho_spearman  pval_spearman  tau_kendall  pval_kendall
0  difficulty         -0.96            0.0        -0.85           0.0
1        size         -0.97            0.0        -0.91           0.0
2  similarity         -0.52            0.0        -0.38           0.0